# -*- mode: ruby -*-
# vi: set ft=ruby :

jenkins_data_disk = "./jenkins_data_disk.vdi"
jenkins_build_disk = "./jenkins_build_disk.vdi"

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.network "private_network", ip: "172.31.31.10"

    jenkins.vm.provider "virtualbox" do |vb|
      vb.name = "Jenkins"
      vb.gui = false
      vb.cpus = 2
      vb.memory = "4096"

      unless File.exist?(jenkins_data_disk)
        vb.customize ['createhd', '--filename', jenkins_data_disk, '--variant', 'Fixed', '--size', 5 * 1024]
      end
      unless File.exist?(jenkins_build_disk)
        vb.customize ['createhd', '--filename', jenkins_build_disk, '--variant', 'Fixed', '--size', 5 * 1024]
      end

      vb.customize ['storageattach', :id,  '--storagectl', 'SCSI', '--port', 2, '--device', 0, '--type', 'hdd', '--medium', jenkins_data_disk]
      vb.customize ['storageattach', :id,  '--storagectl', 'SCSI', '--port', 3, '--device', 0, '--type', 'hdd', '--medium', jenkins_build_disk]     
    end

    jenkins.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "ansible/jenkins.yml"
    end
  end
end