# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  # config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.define "jenkins" do |jenkins|
    config.vm.network "private_network", ip: "172.31.31.10"

    jenkins.vm.provider "virtualbox" do |vb|
      vb.name = "Jenkins"
      vb.gui = false
      vb.cpus = 2
      vb.memory = "4096"
    end

    config.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "ansible/jenkins.yml"
    end
  end
end