# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'

dir = File.dirname(File.expand_path(__FILE__))
ravendbs = YAML.load_file("#{dir}/configs/ravendbs.yml")

Vagrant.configure("2") do |config|
    ravendbs.each do |ravendb|
      CreateVM(config, ravendb)
    end # servers.each     
end # Vagrant

def CreateVM(config, instance)
    instance_name = instance['name']
    
    config.vm.define instance_name do |vm|
        vm.vm.box = "ubuntu/bionic64"
        vm.vm.network "private_network", ip: instance['ip_addr']
        vm.vm.hostname = instance['hostname']

        ConfigureVirtualboxProvider(vm, instance)
        ProvisionVm(vm, instance)
    end # vm
end # CreateVM

def ConfigureVirtualboxProvider(vm, instance)
    instance_name = instance['name']
  
    vm.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.name = instance_name
        vb.cpus = instance['cpu']
        vb.memory = instance['memory']
  
        unless File.exist?("./disks/#{instance_name}-data.vdi")
            vb.customize ['createhd', '--filename', "./disks/#{instance_name}-data.vdi", '--variant', 'Fixed', '--size', "#{instance['disk_size']}"]
        end
        vb.customize ['storageattach', :id, '--storagectl', 'SCSI', '--port', 2, '--device', 0, '--type', 'hdd', '--medium', "./disks/#{instance_name}-data.vdi"]
    end # vb
end # ConfigureVirtualboxProvider

def ProvisionVm(vm, instance)
    UpdateHosts(vm)
    vm.vm.provision "ansible_local" do |ansible|
        ansible.compatibility_mode = "2.0"
        ansible.playbook = 'ansible/ravendb.yml'
        ansible.extra_vars = {
            ip_addr: instance["ip_addr"],
            hostname: instance["hostname"]
        }
        ansible.galaxy_role_file = "ansible/requirements.yml"
        ansible.galaxy_roles_path = "/etc/ansible/roles"
        ansible.galaxy_command = "sudo ansible-galaxy install --role-file=%{role_file} --roles-path=%{roles_path} --force"
    end
end # ProvisionVm

def UpdateHosts(vm)
    vm.vm.provision "shell", inline: <<-SHELL
cat <<-EOF >> /etc/hosts
192.168.56.11 1.ravendb.internal
192.168.56.12 2.ravendb.internal
192.168.56.13 3.ravendb.internal
EOF
   SHELL
end # UpdateHosts