# -*- mode: ruby -*-
# vi: set ft=ruby :

data_disk_1_name = "./disks/data_disk_1.vdi"
data_disk_1_size_mb = 10240

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.name = "Docker with data disk"
    vb.cpus = 2
    vb.memory = 2048

    unless File.exist?(data_disk_1_name)
      vb.customize ['createhd', '--filename', data_disk_1_name, '--variant', 'Fixed', '--size', data_disk_1_size_mb]
    end
    
    vb.customize ['storageattach', :id,  '--storagectl', 'SCSI', '--port', 2, '--device', 0, '--type', 'hdd', '--medium', data_disk_1_name]
  end
  
  config.vm.provision "ansible_local" do |ansible|
    ansible.become = true
    ansible.playbook = "playbook.yml"
    ansible.galaxy_role_file = "requirements.yml"
    ansible.galaxy_roles_path = "/etc/ansible/roles"
    ansible.galaxy_command = "sudo ansible-galaxy install --role-file=%{role_file} --roles-path=%{roles_path} --force"
  end
end
